on: [pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Next.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Set execute permission for script
        run: chmod +x scripts/generate-yarnrc.sh

      - name: Create yarnrc.yml
        run: ./scripts/generate-yarnrc.sh
        env:
          TIPTAP_TOKEN: ${{ secrets.TIPTAP_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint